### ISSUE TITLE
Include named function params when completing a function

### ISSUE THREAD

**Issue by vasiltabakov** [fwcd/KotlinLanguageServer#103]
When completing a function the Complete Item Kind is set as "Snippet". This should ideally happen when the item is resolved, but this is another story.

For now it would be great to at least include the correct and named number of arguments for the function.

Here's a demo of the idea:

RenderCompletionItem.kt
```kotlin
return if (desc.valueParameters.isEmpty())
            "$name()"
        else
            "$name(${desc.valueParameters.mapIndexed { index, vpd -> "\${${index+1}:${vpd.name}}" }.joinToString()})"
```
and how it looks in action:
![2019-03-29_17-06-30](https://user-images.githubusercontent.com/1178309/55242029-10d31200-5245-11e9-9dc6-35055fdeaed9.gif)

I'm using the <kbd>Tab</kbd> key to go to the next param

**Comment by fwcd** [comment]
This looks pretty good and would mimic the behavior of the Java language server.

It should be noted, however, that the language server can already provide signature help:

![image](https://user-images.githubusercontent.com/30873659/55247511-1b42db00-5248-11e9-85c2-edeead2750ad.png)

...which is analogous to the way TypeScript handles completions too:

![image](https://user-images.githubusercontent.com/30873659/55247353-abcceb80-5247-11e9-8b82-2bd51211e01f.png)

Since overloads are displayed as separate completion elements though, I would still vote for your suggestion since it provides a very convenient way of editing parameters.

Could you implement this in a PR?

**Comment by vasiltabakov** [comment]
You're right, I got the idea by comparing how the Java Language Server works.

Will create a PR but will first learn more about how the JLS code works to not miss any considerations they had.

**Comment by jwarkentin** [comment]
Very interested in this, though I don't think I understand enough about how everything works at the moment to confidently do it myself. Any chance we'll see a PR soon? If not, I'll try to find time to dig in an figure it all out but this would be very nice right now. I would love to spend some time improving Kotlin support for VSCode since I hate feeling dependent on Intellij for Kotlin though.

**Comment by vasiltabakov** [comment]
@jwarkentin you can just use the code above to create a custom build or if you're not up to compiling I could send you a version with this 'fix'.

I'm not sure if/when I'll get to a PR because internally at my company we've started building a KLS from scratch for our project. Not sure how compatible it would be with this one, but we can share ideas or parts of the code even tho it will not be open source (for now).
