### ISSUE TITLE
failed to start kotlin lang server

### ISSUE THREAD

**Issue by daihy8759** [fwcd/KotlinLanguageServer#127]
My project is maven project ,
When i open project only show `internal error` popup,and the bottom bar always show 
`activating kotlin language server`.
![image](https://user-images.githubusercontent.com/6057326/61385428-fa7cbf00-a8e4-11e9-839d-8ae8cc16fe94.png)

**Comment by fwcd** [comment]
Is there a way for you to get at the stacktrace of the crash, e.g. by tracing the JSON communication between language server and client? The obscure "Internal Error" popups in VSCode are a known issue (see #123).

**Comment by daihy8759** [comment]
I use console.log to show response message in .vscode/extensions/fwcd.kotlin-0.1.13/node_modules/vscode-jsonrpc/lib/main.js,The chrome developer tools show errors:

![image](https://user-images.githubusercontent.com/6057326/61420429-fd9f9b80-a934-11e9-9222-eb5cb1eaa745.png)

Is there any way show detail stacktrace?

**Comment by fwcd** [comment]
This was fixed in c65b415e7ccbdaf19072e0df750cdf81cdff61e0 but has not been published to the Marketplace yet, so building the language server from scratch should fix it for now.

I have added a test assertion to verify that your artifact is parsed correctly:
https://github.com/fwcd/KotlinLanguageServer/blob/cba6860df327b362f10b36af08fae8fdf3b8b8ec/shared/src/test/kotlin/org/javacs/kt/MavenArtifactParsingTest.kt#L39-L46

**Comment by khe817** [comment]
@fwcd  I saw that new version 0.2.9 is out that fixed this issue, but no new version uploaded to vscode marketplace. Could you please update it there too?

Thanks,

**Comment by fwcd** [comment]
@khe817 Currently in progress, the [new version](https://github.com/fwcd/vscode-kotlin-ide/) will be released to the marketplace later today and feature an auto-updater that automatically fetches the latest language server from GitHub releases!
