### ISSUE TITLE
Main.kt assumes that client suppports workspace/configuration.

### ISSUE THREAD

**Issue by ThoughtTechnician** [fwcd/KotlinLanguageServer#129]
```
  val scope = ConfigurationItem().apply {
       section = "kotlin"
  }
  launcher.remoteProxy.configuration(ConfigurationParams(listOf(scope)))
```
These lines near the bottom of Main.kt will not work in clients that do not support workspace/configuration and cause the server to fail. Tested with ycmd. 

For the time being, I have commented them out, but I perhaps there must be a way to run these lines after we have gotten the client capabilities and checked whether "workspace/configuration" is even one of them.

**Comment by fwcd** [comment]
Thanks for pointing this out, I have removed the section. This call turned out to be redundant anyway, since the server did not use the response.

There seems to be some discussion around the proper usage of `workspace/configuration` (see https://github.com/Microsoft/language-server-protocol/issues/567), so I have opened #131 to address this.

**Comment by c-reeder** [comment]
Great! Thanks for getting back about this so quickly!
