### ISSUE TITLE
Handling 3rd-party jars.

### ISSUE THREAD

**Issue by hifall** [fwcd/KotlinLanguageServer#87]
I am seeing a couple of issues seemingly related to this topic, like #85, but I am not sure how much support this has: I have a Kotlin project that uses 3rd-party jars, and I'd like to use this Kotlin LS to provide auto-completion on these jars.

Is this supported? if so, how do I go about doing it?

Thanks!

**Comment by fwcd** [comment]
@hifall Sure, that's possible. The easiest way to include third party JARs is by using a build tool ([Gradle](https://gradle.org/) and [Maven](https://maven.apache.org/) are supported). A minimal "Hello World" example of a Kotlin project that uses Gradle [can be found here](https://github.com/fwcd/KotlinQuickStart).

Support for projects that neither use Maven nor Gradle (for example pure Eclipse or IDEA projects) [was planned a while ago](https://github.com/fwcd/KotlinLanguageServer/pull/46#issuecomment-409750259) by providing a lightweight config file that lists the JAR dependencies, though I am not sure if that feature is being actively developed. Generally, I would still recommend using a build tool, such as Gradle, since they make dependency management much easier in the long run.

I am closing this issue, but if you have any further questions, feel free to [ask on our Gitter chat](https://gitter.im/fwcd-projects/KotlinLanguageServer).
