### ISSUE TITLE
KotlinLanguageServer not responding to stdout?

### ISSUE THREAD

**Issue by HelgeCPH** [fwcd/KotlinLanguageServer#89]
I am new to the language server protocol and it might be that my question is stupid, however I would appreciate any help. Since I do not know where else to ask it, I am asking here. In case it is not the right place please point me to to a more suitable forum.

Currently, I am working on a [Kotlin kernel for Jupyter](https://github.com/HelgeCPH/kotlin_kernel/tree/lsp_test) for which I would like to use this Kotlin language server for code completion. 

If I understand it right, the language server responds (via stdout) to JSON-RPC calls, which are send via stdin.

However, I cannot get a corresponding response from the server when sending a JSON RPC message. To better explain what I tried to do, I built [a small test](https://github.com/HelgeCPH/kotlin_kernel/blob/lsp_test/tests/test_lsp.py), which sends a JSON RPC request corresponding to hovering over a bit of code. However, it seems as if the Kotlin LSP does not return anything. The test keeps on hanging. It keeps on waiting to read from stdout of the Kotlin LSP after sending the following message:

```
b'Content-Length: 215\r\n\r\n{"jsonrpc": "2.0", "id": 1, "method": "textDocument/hover", "params": {"textDocument": {"uri": "file:///Users/bumm/Documents/documents/python/kotlin_kernel/tests/Hello.kt"}, "position": {"line": 2, "character": 9}}}'
```

But it seems as if there is nothing coming back.

I would expect some kind of response in JSON format (after corresponding headers) containing one or more strings with `inline fun println(message: Any?): Unit`, which would correspond to [the text that is displayed when hovering over line two column nine in](https://github.com/HelgeCPH/kotlin_kernel/blob/lsp_test/tests/Hello.kt), see:

![](https://github.com/HelgeCPH/kotlin_kernel/blob/lsp_test/tests/hover.png?raw=true)

My questions:

  * Is there a way to see the requests and responses between the VSCode plugin and the Kotlin language server?
    - I tried to inspect your test-suite but all communication between the client and the server is wrapped in code and I cannot find where that code is translated to JSON RPC format.
    - I see your [comment on debugging in BUILDING.md](https://github.com/fwcd/KotlinLanguageServer/blob/master/BUILDING.md#debugging). Is this where I could see the messages directly? If so, what do I have to do precisely? Unfortunately, I do not really understand the comment.
  * Do I have to send other JSON RPC requests to the server before sending the one to hover?
    - If so, why does the server not return an error message? Currently, it is just silent.
  

Everything that I know about the LSP so far comes from it's specification document: https://microsoft.github.io/language-server-protocol/specification
Consequently, I would really appreciate any help.

**Comment by fwcd** [comment]
First of all, thanks for providing such a detailed description of the issue.

Currently, the JSON-RPC communication is performed by [LSP4J library](https://github.com/eclipse/lsp4j), which makes it a bit tricky to inspect JSON messages directly.

Looking at your test, I found out that flushing `proc.stdin` after writing solves the fundamental issue (since Python streams are buffered). However, the language server sends additional log messages such as

```json
{"jsonrpc": "2.0", "method": "window/logMessage", "params": {"type": 3, "message": "async0    Hovering at file://D:\\git\\kotlin_kernel\\tests\\Hello.kt 1:9"}}
```

...which your test assertion is currently not prepared to handle:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\git\kotlin_kernel\tests\test_lsp.py", line 89, in test_hover
AttributeError: 'dict' object has no attribute 'decode'
```

(These log messages can be inspected from VSCode by the way:

![image](https://user-images.githubusercontent.com/30873659/53302147-7d7c7a80-385b-11e9-98e3-b81c58f9b998.png))

Additionally, the language server relies on the client sending an `initialize`-request and registering a workspace folder... adding external files [is experimental](https://github.com/fwcd/KotlinLanguageServer/commit/3cb1cfaea83336f6399834f02864dbe265d876b4) at the moment. I have submitted a PR to your repository that fixes the issue: https://github.com/HelgeCPH/kotlin_kernel/pull/1

**Comment by fwcd** [comment]
Feel free to open new issues if there are any problems or use the Gitter chat: [![Gitter](https://badges.gitter.im/fwcd-projects/KotlinLanguageServer.png)](https://gitter.im/fwcd-projects/KotlinLanguageServer) 👍

**Comment by HelgeCPH** [comment]
Thank you very much for your help! I really appreciate that you had a look on the test and all your work on it. That is really helpful. In particular your description and implementation of the extra messages that are necessary for setting up the workspace and the additional messages that the server help me a lot. I learned quite a bit from your test implementation. I just merged the pull request and will soon start working on trying to integrate code completion to the Jupyter kernel accordingly. I will let you know when I have something working.

Of course I forgot to flush to really write out the messages... Thank you for pointing me to that :)
