### ISSUE TITLE
Request methods

### ISSUE THREAD

**Issue by joncarr** [fwcd/KotlinLanguageServer#90]
Hi, I'm writing a PR (for emacs-lsp) to add out-of-the-box kotlin-language-server support for emacs and lsp-mode. Everything appears to be going great but I have one warning I can't get to go away. The error is `Unknown request method: workspace/configuration`. So my question is, where might I find the details for this request method inside the kotlin-language-server code so I can write a handler to satisfy it's requirements???

**Comment by fwcd** [comment]
Thanks for your suggestion! The method [`workspace/configuration`](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration) is not (yet) supported, but would be added in [`KotlinWorkspaceService.kt`](https://github.com/fwcd/KotlinLanguageServer/blob/master/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt) by overriding the appropriate method.

**Comment by fwcd** [comment]
(Edit) Thanks for your suggestion!

The [`workspace/configuration`](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration) method seems to have been introduced in LSP 3.6, is it supported by `emacs-lsp`? Since this is a request sent from the server to the client, so it might not be server issue.

Most workspace-related code is located in [`KotlinWorkspaceService.kt`](https://github.com/fwcd/KotlinLanguageServer/blob/master/src/main/kotlin/org/javacs/kt/KotlinWorkspaceService.kt).

**Comment by joncarr** [comment]
I'm going to be honest with you.  I'm not entirely sure to be honest!!!  I really don't know a lot about LSP but `emacs-lsp` does not support `kotlin-language-server` out of the box, so I figured it would be easy enough to just add that support.  I'll look into the `emacs-lsp` side and see what I can dig up.  Initial digs through that code didn't show me any other handlers for `workspace/configuration`.  I'll go look more thoroughly right now and see what I can figure out! :)

**Comment by fwcd** [comment]
Should be fixed with #129.
